### ISSUE TITLE
Am getting this error when importing CoreML Model 

### ISSUE THREAD

**Issue by Ruman1234** [fritzlabs/heartbeat-ios#18]
<img width="676" alt="Screen Shot 2019-07-16 at 3 21 28 PM" src="https://user-images.githubusercontent.com/37799754/61286975-6aa01d80-a7dd-11e9-906d-704ce6b767cc.png">
#CoreML

**Comment by jamesonthecrow** [comment]
It seems like your Core ML model is corrupted or was perhaps created with a different version of Core ML than the one your system supports. Given that this model is external to this repository and one we cannot verify the origins of, I'm going to close this issue.

We're still happy to help you get this resolved, though. You can join the [Heartbeat Slack](bit.ly/heartbeatslack) where we can assist you.

**Comment by Ruman1234** [comment]
then why SqueezeNet.mlmodel is working fine i there is some version issue

**Comment by ghop02** [comment]
It seems like you are using an old version of Heartbeat.  Is there a reason why?

**Comment by Ruman1234** [comment]
no my Xcode is Version 10.2.1 (10E1001)
