### ISSUE TITLE
mlmodel files: unable to deserialize object

### ISSUE THREAD

**Issue by kirualex** [fritzlabs/heartbeat-ios#4]
Unsure if this is caused by Xcode 9.3, but I get the following errors on every models : 
<img width="503" alt="capture d ecran 2018-04-02 a 16 27 31" src="https://user-images.githubusercontent.com/431974/38199937-c29364ba-3692-11e8-9e5a-cad47a84efb0.png">

**Comment by AndrewBarba** [comment]
Yes could be, taking a look now. Stay tuned

**Comment by AndrewBarba** [comment]
@kirualex Actually I think this due to the models being stores in git using LFS:

https://git-lfs.github.com

Can you try installing that, deleting directory, and re-cloning the project?

I should have included that in the readme, will update now

**Comment by AndrewBarba** [comment]
I also just updated the Fritz Framework, and this repo, to build with Xcode 9.3 and Swift 4.1. Let me know if you are still having issues

**Comment by kirualex** [comment]
Working like a charm with git-lfs 👍
